# Generated by Django 5.0.9 on 2024-09-15 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body_homepage_heading_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='meta_title',
        ),
    ]
