# Generated by Django 5.0.9 on 2024-09-16 01:07

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_homepage_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='menubox',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
