# Generated by Django 5.0.9 on 2024-10-11 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_menubox'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomePage',
            new_name='HomeIndexPage',
        ),
    ]
