# Generated by Django 5.0.9 on 2024-10-15 17:44

import home.models
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_notice_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('product_table', 5), ('notice', 6), ('raw_html', 7)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {}), 4: ('wagtail.blocks.ListBlock', (home.models.ProductBlock,), {}), 5: ('wagtail.blocks.StructBlock', [[('heading', 3), ('description', 1), ('products', 4)]], {}), 6: ('wagtail.snippets.blocks.SnippetChooserBlock', (home.models.Notice,), {}), 7: ('wagtail.blocks.RawHTMLBlock', (), {})}),
        ),
    ]
